const express = require("express");
const cors = require("cors");
const fetch = require("node-fetch");

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json({ limit: "1mb" }));

app.get("/", (req, res) => res.send("RebLaw AI Proxy is running."));
app.get("/health", (req, res) => res.json({ ok: true }));

function normalizeIncoming(reqBody) {
  const body = reqBody || {};

  // WordPress plugin sends { messages:[...], meta:{...} }
  if (Array.isArray(body.messages) && body.messages.length) {
    return { messages: body.messages, meta: body.meta || {} };
  }

  // Older/simple clients send { question:"..." }
  if (typeof body.question === "string" && body.question.trim()) {
    return {
      messages: [
        {
          role: "system",
          content:
            "You are a helpful legal assistant. Answer clearly and practically. End with a brief disclaimer that this is not a substitute for professional legal advice.",
        },
        { role: "user", content: body.question.trim() },
      ],
      meta: body.meta || {},
    };
  }

  return null;
}

async function handleAsk(req, res) {
  const normalized = normalizeIncoming(req.body);
  if (!normalized) {
    return res.status(400).json({
      success: false,
      message: "Invalid payload. Send {messages:[...]} or {question:\"...\"}.",
    });
  }

  if (!process.env.OPENAI_API_KEY) {
    return res.status(500).json({
      success: false,
      message: "OPENAI_API_KEY is not set on the server.",
    });
  }

  const model = process.env.OPENAI_MODEL || "gpt-4o-mini";

  try {
    const openaiResponse = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model,
        messages: normalized.messages,
        temperature: 0.3,
      }),
    });

    const data = await openaiResponse.json();

    if (!openaiResponse.ok) {
      console.error("OpenAI error status:", openaiResponse.status);
      console.error("OpenAI error body:", data);
      return res.status(openaiResponse.status).json({
        success: false,
        message: "OpenAI API error",
        details: data,
      });
    }

    const answer = data?.choices?.[0]?.message?.content?.trim();

    if (!answer) {
      return res.status(502).json({
        success: false,
        message: "No answer generated by AI.",
        details: data,
      });
    }

    return res.json({ success: true, answer });
  } catch (err) {
    console.error("Proxy server error:", err);
    return res.status(500).json({
      success: false,
      message: "Proxy server error",
    });
  }
}

app.post("/ask", handleAsk);
app.post("/api/ask", handleAsk);

app.listen(PORT, "0.0.0.0", () => {
  console.log(`RebLaw AI Proxy listening on port ${PORT}`);
});
