const express = require("express");
const cors = require("cors");
const fetch = require("node-fetch");

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

app.get("/", (req, res) => {
  res.send("RebLaw AI Proxy is running.");
});

app.post("/ask", async (req, res) => {
  const { question } = req.body;

  if (!question) {
    return res.status(400).json({ error: "No question provided" });
  }

  try {
    const openaiResponse = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${process.env.OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
          model: "gpt-3.5-turbo",
 // در صورت نیاز می‌توانیم مدل را عوض کنیم
        messages: [
          {
            role: "system",
            content: "You are a helpful legal assistant. Answer clearly and practically.",
          },
          {
            role: "user",
            content: question,
          },
        ],
      }),
    });

    const data = await openaiResponse.json();

    if (!openaiResponse.ok) {
      console.error("OpenAI error:", data);
      return res.status(openaiResponse.status).json({
        error: "OpenAI API error",
        details: data,
      });
    }

    const answer =
      data?.choices?.[0]?.message?.content?.trim() ||
      "No answer generated by AI.";

    return res.json({ answer });

  } catch (err) {
    console.error("Proxy server error:", err);
    return res.status(500).json({ error: "Proxy server error" });
  }
});

app.listen(PORT, () => {
  console.log(`RebLaw AI Proxy listening on port ${PORT}`);
});
